name: CI - Tests and Coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Black (check only)
        run: |
          black --version
          black --check .

      - name: Run tests with coverage
        run: |
          pytest -v --cov=src --cov-branch --cov-report=xml:coverage.xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          # Set token in repository secrets if private repo
          token: ${{ secrets.CODECOV_TOKEN }}
